### ISSUE TITLE
修复kubeplay安装节点和其他节点的containerd版本不一致问题，调整nerdctl的版本到v0.14.0,验证是否可以build镜像

### ISSUE THREAD

**Issue by mytting** [deepflow-kubeplay/kubeplay#2]
### 原因：

​     因原来的nerdctl-full 包中有完整的containerd ，并且版本与kubespray的版本不一致，导致安装的k8s节点containerd版本不一致  
​    
kubectl get node -o wide可以看到

### 改动：

​     不使用nerdctl-full包，使用只包含二进制文件的包

​     修改kubespray的nerdctl版本为v0.14.0，并默认在所有节点安装nerdctl工具

### 验证：

验证是否可以正常安装

```
kubectl get node -o wide ## 查看所有节点的containerd版本是否为1.4.9
nerdctl --version ###验证nerdctl的版本
```

  写一个简单的Dockerfile 验证是否可以build

```
mkdir new_dir
vi Dockerfile

FROM centos:7

nerdctl build -t xxx .
```

**Comment by shanren-kaka** [comment]
containerd版本确实切换至为1.4.9，

**Comment by shanren-kaka** [comment]
containerd版本确实切换至1.4.9，但nerdctl build 报```FATA[0000] `buildctl` needs to be installed and `buildkitd` needs to be running, see https://github.com/moby/buildkit: exec: "buildctl": executable file not found in $PATH```

**Comment by mytting** [comment]
关于 nerdctl build 的问题后续在另一个issues  #7 中讨论
此issues在其他的问题都解决后close @shanren-kaka
