### ISSUE TITLE
kubelet pod log dir 在某些特殊情况下可能会出现目录软连接不正常，无法写入日志数据，导致kubeadm初始化失败

### ISSUE THREAD

**Issue by mytting** [deepflow-kubeplay/kubeplay#9]
kubelet pod log dir 在某些特殊情况下可能会出现目录软连接不正常，无法写入日志数据，导致kubeadm初始化失败

## 环境：

 光大测试环境安装k8s集群出现的问题
  目录结构：
   /var/log -->/mnt/vdc1/log
   /var/log/pods--> /mnt/vdc1/log/pod

## 操作系统：centos7.5

@shanren-kaka 看看能否复现

**Comment by mytting** [comment]
降低优先级。最后再搞

**Comment by mytting** [comment]
针对这个问题 目前做了一些优化
  pods_log_dir: "{{ data_dir }}/pod_log/pods"
这个变量如果值不等于/var/log/pods，那就建一个{{ data_dir }}/pod_log/pods到/var/log/pods的软连接
如果为空或者等于/var/log/pods，就不操作这个目录

**Comment by shanren-kaka** [comment]
新beta中已解决。
